// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vessel/vessel.proto

/*
Package go_micro_srv_vessel is a generated protocol buffer package.

It is generated from these files:
	proto/vessel/vessel.proto

It has these top-level messages:
	Vessel
	Specification
	Response
*/
package go_micro_srv_vessel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vessel struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Capacity  int32  `protobuf:"varint,2,opt,name=capacity" json:"capacity,omitempty"`
	MaxWeight int32  `protobuf:"varint,3,opt,name=max_weight,json=maxWeight" json:"max_weight,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Available bool   `protobuf:"varint,5,opt,name=available" json:"available,omitempty"`
	OwnerId   string `protobuf:"bytes,6,opt,name=owner_id,json=ownerId" json:"owner_id,omitempty"`
}

func (m *Vessel) Reset()                    { *m = Vessel{} }
func (m *Vessel) String() string            { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()               {}
func (*Vessel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type Specification struct {
	Capacity  int32 `protobuf:"varint,1,opt,name=capacity" json:"capacity,omitempty"`
	MaxWeight int32 `protobuf:"varint,2,opt,name=max_weight,json=maxWeight" json:"max_weight,omitempty"`
}

func (m *Specification) Reset()                    { *m = Specification{} }
func (m *Specification) String() string            { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()               {}
func (*Specification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Specification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

type Response struct {
	Vessel  *Vessel   `protobuf:"bytes,1,opt,name=vessel" json:"vessel,omitempty"`
	Vesels  []*Vessel `protobuf:"bytes,2,rep,name=vesels" json:"vesels,omitempty"`
	Created bool      `protobuf:"varint,3,opt,name=created" json:"created,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Response) GetVesels() []*Vessel {
	if m != nil {
		return m.Vesels
	}
	return nil
}

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func init() {
	proto.RegisterType((*Vessel)(nil), "go.micro.srv.vessel.Vessel")
	proto.RegisterType((*Specification)(nil), "go.micro.srv.vessel.Specification")
	proto.RegisterType((*Response)(nil), "go.micro.srv.vessel.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VesselService service

type VesselServiceClient interface {
	FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error)
	Create(ctx context.Context, in *Vessel, opts ...client.CallOption) (*Response, error)
}

type vesselServiceClient struct {
	c           client.Client
	serviceName string
}

func NewVesselServiceClient(serviceName string, c client.Client) VesselServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.vessel"
	}
	return &vesselServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *vesselServiceClient) FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.FindAvailable", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselServiceClient) Create(ctx context.Context, in *Vessel, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VesselService service

type VesselServiceHandler interface {
	FindAvailable(context.Context, *Specification, *Response) error
	Create(context.Context, *Vessel, *Response) error
}

func RegisterVesselServiceHandler(s server.Server, hdlr VesselServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&VesselService{hdlr}, opts...))
}

type VesselService struct {
	VesselServiceHandler
}

func (h *VesselService) FindAvailable(ctx context.Context, in *Specification, out *Response) error {
	return h.VesselServiceHandler.FindAvailable(ctx, in, out)
}

func (h *VesselService) Create(ctx context.Context, in *Vessel, out *Response) error {
	return h.VesselServiceHandler.Create(ctx, in, out)
}

func init() { proto.RegisterFile("proto/vessel/vessel.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4e, 0xea, 0x40,
	0x14, 0xc6, 0xef, 0x14, 0x28, 0xe5, 0xdc, 0xe0, 0xe2, 0xb8, 0x19, 0x50, 0x92, 0xa6, 0x2b, 0x56,
	0x35, 0x81, 0x27, 0x30, 0x26, 0x24, 0xba, 0x2c, 0x46, 0x97, 0x64, 0x98, 0x1e, 0x71, 0x92, 0xb6,
	0xd3, 0xcc, 0x34, 0x05, 0x5f, 0xc2, 0x67, 0xf0, 0x05, 0x7c, 0x47, 0x93, 0x29, 0x60, 0x30, 0x0d,
	0xba, 0xea, 0xf9, 0xfb, 0x9d, 0xaf, 0xbf, 0x0c, 0x8c, 0x4a, 0xa3, 0x2b, 0x7d, 0x53, 0x93, 0xb5,
	0x94, 0xed, 0x3f, 0xb1, 0xab, 0xe1, 0xe5, 0x46, 0xc7, 0xb9, 0x92, 0x46, 0xc7, 0xd6, 0xd4, 0x71,
	0xd3, 0x8a, 0x3e, 0x18, 0xf8, 0x4f, 0x2e, 0xc4, 0x0b, 0xf0, 0x54, 0xca, 0x59, 0xc8, 0xa6, 0x83,
	0xc4, 0x53, 0x29, 0x8e, 0x21, 0x90, 0xa2, 0x14, 0x52, 0x55, 0x6f, 0xdc, 0x0b, 0xd9, 0xb4, 0x97,
	0x1c, 0x73, 0x9c, 0x00, 0xe4, 0x62, 0xb7, 0xda, 0x92, 0xda, 0xbc, 0x56, 0xbc, 0xe3, 0xba, 0x83,
	0x5c, 0xec, 0x9e, 0x5d, 0x01, 0x11, 0xba, 0x85, 0xc8, 0x89, 0x77, 0x9d, 0x98, 0x8b, 0xf1, 0x1a,
	0x06, 0xa2, 0x16, 0x2a, 0x13, 0xeb, 0x8c, 0x78, 0x2f, 0x64, 0xd3, 0x20, 0xf9, 0x2e, 0xe0, 0x08,
	0x02, 0xbd, 0x2d, 0xc8, 0xac, 0x54, 0xca, 0x7d, 0xb7, 0xd5, 0x77, 0xf9, 0x7d, 0x1a, 0x3d, 0xc0,
	0x70, 0x59, 0x92, 0x54, 0x2f, 0x4a, 0x8a, 0x4a, 0xe9, 0xe2, 0xc4, 0x18, 0x3b, 0x6b, 0xcc, 0xfb,
	0x61, 0x2c, 0x7a, 0x67, 0x10, 0x24, 0x64, 0x4b, 0x5d, 0x58, 0xc2, 0x39, 0xf8, 0x0d, 0x05, 0xa7,
	0xf2, 0x7f, 0x76, 0x15, 0xb7, 0x10, 0x8a, 0x1b, 0x3a, 0xc9, 0x7e, 0x74, 0xbf, 0x44, 0x99, 0xe5,
	0x5e, 0xd8, 0xf9, 0xcb, 0x12, 0x65, 0x16, 0x39, 0xf4, 0xa5, 0x21, 0x51, 0x51, 0xea, 0x58, 0x05,
	0xc9, 0x21, 0x9d, 0x7d, 0x32, 0x18, 0x36, 0xc3, 0x4b, 0x32, 0xb5, 0x92, 0x84, 0x8f, 0x30, 0x5c,
	0xa8, 0x22, 0xbd, 0x3d, 0xa2, 0x89, 0x5a, 0x2f, 0x9c, 0x20, 0x19, 0x4f, 0x5a, 0x67, 0x0e, 0x7f,
	0x1a, 0xfd, 0xc3, 0x05, 0xf8, 0x77, 0xee, 0x24, 0x9e, 0x33, 0xfc, 0xab, 0xce, 0xda, 0x77, 0x6f,
	0x69, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff, 0x14, 0x93, 0x85, 0xfa, 0x68, 0x02, 0x00, 0x00,
}
